export const categories = [
  { id: 'dessert',         label: 'קינוחים',       order: 1 },
  { id: 'special-morning', label: 'בוקר מיוחד',    order: 2 },
  { id: 'personal-pastry', label: 'מאפה אישי',     order: 3 },
  { id: 'sandwish',        label: 'סנדוויצ\'ים',   order: 4 },
  { id: 'hot-drinks',      label: 'משקאות חמים',   order: 5 },
  { id: 'cold-drinks',     label: 'משקאות קרים',   order: 6 },
];

export const items = [
  // ── קינוחים ──────────────────────────────────────────────────────────
  { id: '1',  categoryId: 'dessert', name: 'גבינה אפויה',          price: 32, img: '/menu/גבינה מרינג.jpeg',              desc: 'עוגת גבינה קלאסית אורירית וקלה' },
  { id: '2',  categoryId: 'dessert', name: 'גבינה ותות',           price: 34, img: '/menu/גבינה תות.jpeg',               desc: 'עוגת גבינה על מצע עוגיות חמאה בציפוי קונפיטורת תות' },
  { id: '3',  categoryId: 'dessert', name: 'גבינה אוראו',          price: 34, img: '/menu/גבינה אוראו.jpeg',             desc: 'מצע של בצק פריך, גבינה אפויה קרם וניל עם עוגיות אוראו. בציפוי שנטילי וניל ואוראו' },
  { id: '4',  categoryId: 'dessert', name: 'גבינת פירורים',        price: 32, img: '/menu/cheese and crumbs.webp',       desc: 'גבינה קטיפתית עשירה ומעל פרורי בצק פריך חמאתי', note: 'אפשרות ללא תוספת סוכר' },
  { id: '5',  categoryId: 'dessert', name: 'טירמיסו',              price: 33, img: '/menu/טירמיסו.jpeg',                desc: 'שכבות של בישקוטים ספוגים באספרסו, קרם גבינת מסקרפונה וקפה, בעיטור קקאו' },
  { id: '6',  categoryId: 'dessert', name: 'שוקולטה',              price: 37, img: '/menu/chocolata.webp',              desc: 'מפגש פסגה של עוגת שוקולד מריר עם שוקולד פרלין ומעל תלתלים של שוקולד בלגי לבן', note: 'עוגה חמה' },
  { id: '7',  categoryId: 'dessert', name: 'שוקולד חמאת בוטנים',   price: 34, img: '/menu/1.png',                       desc: 'מוס שוקולד חמאת בוטנים, בעיטור קראנץ שוקולד בלגי ומקרון אדום' },
  { id: '8',  categoryId: 'dessert', name: 'שוקולד בלגי ללא סוכר', price: 33, img: '/menu/no sugar.png',               desc: 'קרם שוקולד בלגי איכותי ללא סוכר בציפוי גנאש שוקולד מריר על מצע של בצק פריך שוקולד' },
  { id: '9',  categoryId: 'dessert', name: 'תפוחים פאי',           price: 35, img: '/menu/קראמבל-תפוחים-1.jpg',         desc: 'פאי תפוחים בשילוב קינמון במעטפת פירורי בצק שטרוייזל', note: 'מוגש חם • אפשרות ללא סוכר' },
  { id: '10', categoryId: 'dessert', name: 'פאי אגוזים',           price: 35, img: '/menu/אגוזים temp.jpeg',           desc: 'אגוזי מלך לוז ופקאן מקורמלים בטופי, אפויים בתוך פאי של בצק פריך', note: 'מוגש חם' },
  { id: '11', categoryId: 'dessert', name: 'קינדר',                price: 32, img: '/menu/kinder.webp',                desc: 'מוס קינדר על שכבת קראנצ׳ שוקולדים ובראוניס בציפוי גנאש שוקולד חלב עשיר' },
  { id: '12', categoryId: 'dessert', name: 'טריקולד',              price: 33, img: '/menu/trekolad.webp',              desc: 'שלוש שכבות של שוקולד בלגי משובח: מריר, חלב ולבן' },
  { id: '13', categoryId: 'dessert', name: 'לוטוס',                price: 32, img: '/menu/loutus.webp',               desc: 'קרם לוטוס וגבינת שמנת עשירה על בסיס קרמבל עוגיות לוטוס פריך בציפוי ממרח לוטוס' },
  { id: '14', categoryId: 'dessert', name: 'עוגת אלפחורס',         price: 33, img: '/menu/אלפחורוס.jpeg',             desc: 'בסיס עוגיית אלפחורס גדולה, קרם ריבת חלב, ליבת קרם קוקוס, דקואז קוקוס, בציפוי גלאסז׳ קרמל' },
  { id: '15', categoryId: 'dessert', name: 'סופלה אלפרדו',         price: 33, img: '/menu/surprise.webp',             desc: 'פונדנט שוקולד חם עם טראפל שוקולד לבן בתוכו בציפוי של גנאש שוקולד חלב', note: 'עוגה חמה' },
  { id: '16', categoryId: 'dessert', name: 'מאפינס שוקולד',        price: 13, img: '/menu/מאפינס שוקו.jpeg' },
  { id: '17', categoryId: 'dessert', name: 'סברינה',               price: 20, img: '/menu/sabarina.webp',             desc: 'בצק אורירי ספוג בסירופ נהדר ומעליו שמנת מתוקה טרייה' },
  { id: '18', categoryId: 'dessert', name: 'כדורי שוקולד',         price: 5,  img: '/menu/chocolate-balls.webp',      desc: 'כדורי שוקולד בלגי איכותי בציפוי קוקוס' },
  { id: '19', categoryId: 'dessert', name: 'גליליות ארוכות',       price: 12, img: '/menu/katsrot.webp',              desc: 'גלילית ופל במילוי שמנת מתוקה וציפוי שוקולד בלגי' },
  { id: '20', categoryId: 'dessert', name: 'אלפחורס',              price: 10, img: '/menu/alphakores.webp',           desc: 'כריך משתי עוגיות שביניהן מרוחה ריבת חלב' },
  { id: '21', categoryId: 'dessert', name: 'דונאט',                price: 10, img: '/menu/donuts 2.webp' },

  // ── בוקר מיוחד ───────────────────────────────────────────────────────
  { id: '22', categoryId: 'special-morning', name: 'סלט אישי',                  price: 25, img: '/menu/סלט עלים וחסה.png',  desc: 'חסה, עגבניות שירי צבעוני, בצל סגול, אגוזים, גבינה בולגרית' },
  { id: '23', categoryId: 'special-morning', name: 'סלט אישי טונה',             price: 45, img: '/menu/סלטטונה.png',        desc: 'חסה, עגבניות, בצל סגול, טונה (26 גרם חלבון), ביצה קשה, גבינה בולגרית ואגוזים' },
  { id: '26', categoryId: 'special-morning', name: 'פאי עגבניות שירי',          price: 49, img: '/menu/paitometo.png',      desc: 'בצק פריך, גבינות ורויאל במילוי עגבניות שרי ומוצרלה, מוגשת עם סלט אישי קטן לבחירה' },
  { id: '27', categoryId: 'special-morning', name: 'פאי אנטיפסטי',             price: 49, img: '/menu/paiantipasti.png',   desc: 'בצק פריך, גבינות ורויאל במילוי זוקיני, פלפלים, חצילים, ובטטות, מוגשת עם סלט אישי קטן לבחירה' },
  { id: '28', categoryId: 'special-morning', name: 'סנדוויץ בורקס',             price: 25, img: '/menu/סנדוויץ.webp',      desc: 'גבינה או תפוח אדמה, רוטב פסטו, עגבניות, מלפפון חמוץ', extras: [{ label: 'ביצה קשה', price: 5 }] },
  { id: '29', categoryId: 'special-morning', name: 'בורקס עגלה',                price: 25, img: '/menu/עגלה.webp',         desc: 'גבינה / תפוח אדמה / פטריות, מוגש עם מלפפון חמוץ זיתים ורוטב עגבניות', extras: [{ label: 'תרד וגבינה', price: 3 }, { label: 'ביצה', price: 5 }] },
  { id: '30', categoryId: 'special-morning', name: 'טוסט הבית',                 price: 30, img: '/menu/toast.webp',        desc: 'מיקס גבינה צהובה ובולגרית עם רוטב הבית, זיתים ותירס' },
  { id: '31', categoryId: 'special-morning', name: 'פיתה עם זעתר',              price: 14, img: '/menu/za3tar.webp' },
  { id: '32', categoryId: 'special-morning', name: 'פיתה עם בצל',               price: 16, img: '/menu/בצל.webp' },
  { id: '33', categoryId: 'special-morning', name: 'פיתה עם גבינה',             price: 17, img: '/menu/cheesejpg.webp' },
  { id: '34', categoryId: 'special-morning', name: 'פיצה אישית',                price: 18, img: '/menu/פיצה.webp',         desc: 'תוספות: זיתים / תירס', extras: [{ label: 'זיתים ותירס', price: 2 }] },
  { id: '35', categoryId: 'special-morning', name: 'שתי מקלות גבינה',           price: 20, img: '/menu/מקלל.webp',         desc: 'גבינה / גבינה חריפה', extras: [{ label: 'מקל נוסף', price: 8 }] },
  { id: '36', categoryId: 'special-morning', name: 'בורקס אישי גבינה / תפו"א',  price: 17, img: '/menu/אישי גבינה.webp' },

  // ── מאפה אישי ────────────────────────────────────────────────────────
  { id: '37', categoryId: 'personal-pastry', name: 'קרואסון חמאה',   price: 10, img: '/menu/חמאה.webp' },
  { id: '38', categoryId: 'personal-pastry', name: 'קרואסון שוקולד', price: 10, img: '/menu/croissant.webp' },
  { id: '39', categoryId: 'personal-pastry', name: 'קרואסון שקדים',  price: 10, img: '/menu/שקדים 12.jpg' },
  { id: '40', categoryId: 'personal-pastry', name: 'חלבה שוקולד',    price: 10, img: '/menu/חלבה.webp' },
  { id: '41', categoryId: 'personal-pastry', name: 'קרואסון גבינה',  price: 10, img: '/menu/גביניותjpg.webp' },
  { id: '42', categoryId: 'personal-pastry', name: 'קינמון',         price: 10, img: '/menu/קינמון אישי.webp' },
  { id: '43', categoryId: 'personal-pastry', name: 'רוגלך',          price: 10, img: '/menu/רוגלך.webp' },
  { id: '44', categoryId: 'personal-pastry', name: 'מאפינס שוקולד',  price: 13, img: '/menu/מאפינס שוקו.jpeg' },

  // ── סנדוויצ'ים ───────────────────────────────────────────────────────
  { id: '45', categoryId: 'sandwish', name: 'ברוסקטה אבוקדו',            price: 48, img: '/menu/ברוסקטה אבוקדו.png',           desc: 'שתי פרוסות אבוקדו עם לבנה 5% (לחם מחמצת ללא סוכר), מוגשת עם שתי ביצים קשות, צלחת טונה, זיתים ירוקים וסלט אישי קטן' },
  { id: '46', categoryId: 'sandwish', name: 'ברוסקטה סלמון מעושן',        price: 55, img: '/menu/ברוסקטה סלמון.png',            desc: 'שתי פרוסות סלמון מעושן עם גבינת שמנת (לחם מחמצת ללא סוכר), מוגשת עם שתי ביצים קשות, צלחת אבוקדו, זיתים ירוקים וסלט' },
  { id: '47', categoryId: 'sandwish', name: 'The Club Sandwich',           price: 45, img: '/menu/the club.png',                 desc: 'סנדוויץ אווז, סלמי, גבינה צהובה, גבינת שמנת, ממרח פלפלים, עגבניות, ומלפפון חמוץ, מוגש עם קראנצ׳ ציפס' },
  { id: '48', categoryId: 'sandwish', name: 'קרואסון סלמון מעושן',        price: 55, img: '/menu/קרואסון סלמון חדש.png',        desc: 'קרואסון חמאה אישי, סלמון מעושן, גבינת שמנת, חסה, מלפפון חמוץ, בצל סגול, וגרידת פרמזן', extras: [{ label: 'אבוקדו', price: 7 }, { label: 'ביצה', price: 5 }] },
  { id: '49', categoryId: 'sandwish', name: 'קרואסון אווז וגבינה מעושנת', price: 35, img: '/menu/אווז וגבינה מעושנת חדש.png', desc: 'קרואסון חמאה אישי, אווז, גבינה מעושנת, חסה, מלפפון חמוץ', extras: [{ label: 'אבוקדו', price: 7 }, { label: 'ביצה', price: 5 }] },
  { id: '50', categoryId: 'sandwish', name: 'המיוחד שלנו',                price: 35, img: '/menu/פרינה.webp',                  desc: 'לחם פרינה עם כתף בקר וגבינה צהובה על פלטה חמה, רוטב פסטו ואיולי, חסה ומלפפון חמוץ' },
  { id: '51', categoryId: 'sandwish', name: 'כריך אבוקדו',                price: 35, img: '/menu/avocado.jpg',                 desc: 'לחם פרינה עם אבוקדו, בצל סגול, עגבניות, וחסה' },
  { id: '52', categoryId: 'sandwish', name: 'גבטה בולגרית',               price: 25, img: '/menu/בולגרית.webp',               desc: 'לבחירה גבטה כפרית / גבטה רגילה, רוטב פסטו, עגבניות, חסה, מלפפון חמוץ' },
  { id: '53', categoryId: 'sandwish', name: 'בגט / גבטה טונה',            price: 30, img: '/menu/גבטה טונה.png',              desc: 'לבחירה לחם כפרי / לחם רגיל, חסה, בצל, מלפפון חמוץ, ממרח מיונז עם תירס וזעתר', extras: [{ label: 'ביצה', price: 5 }] },
  { id: '54', categoryId: 'sandwish', name: 'בגט נקניקיות גריל',          price: 22, img: '/menu/hotdog.webp',                desc: 'נקניקיות חריפות / רגילות כולל כל התוספות' },

  // ── משקאות חמים ──────────────────────────────────────────────────────
  { id: '55', categoryId: 'hot-drinks', name: 'סחלב',                price: 20, img: '/menu/סחלבjpeg.webp' },
  { id: '56', categoryId: 'hot-drinks', name: 'לאטה וניל',           price: 18, img: '/menu/vanilla.png' },
  { id: '57', categoryId: 'hot-drinks', name: 'לאטה קרמל',           price: 18, img: '/menu/caramel.png' },
  { id: '58', categoryId: 'hot-drinks', name: 'לאטה שוקולד',         price: 18, img: '/menu/chocolate.png' },
  { id: '59', categoryId: 'hot-drinks', name: 'טופי אספרסו',         price: 14, img: '/menu/toffe.png' },
  { id: '60', categoryId: 'hot-drinks', name: 'מקיאטו שוקולד',       price: 14, img: '/menu/macchiato.png' },
  { id: '61', categoryId: 'hot-drinks', name: 'Triple Chocolate',     price: 18, img: '/menu/triple.png' },
  { id: '62', categoryId: 'hot-drinks', name: 'הפוך / קפוצ׳ינו / נס', price: 15, img: '/menu/latte.webp' },
  { id: '63', categoryId: 'hot-drinks', name: 'אספרסו',              price: 7,  img: '/menu/espresso.webp', sizes: [{ label: 'קצר', price: 7 }, { label: 'ארוך', price: 7 }, { label: 'כפול', price: 14 }] },
  { id: '64', categoryId: 'hot-drinks', name: 'שוקו חם',             price: 15, img: '/menu/hotchocolate.webp', extras: [{ label: 'מרשמלו', price: 5 }, { label: 'קצפת', price: 3 }] },
  { id: '65', categoryId: 'hot-drinks', name: 'אמריקנו',             price: 10, img: '/menu/americano.webp' },
  { id: '66', categoryId: 'hot-drinks', name: 'מקיאטו',              price: 10, img: '/menu/macchiato.webp' },
  { id: '67', categoryId: 'hot-drinks', name: 'תה',                  price: 12, img: '/menu/tea.webp',    note: 'קנקן תה ליחיד ₪20' },
  { id: '68', categoryId: 'hot-drinks', name: 'קנקן תה',             price: 28, img: '/menu/teaנןע.png' },

  // ── משקאות קרים ──────────────────────────────────────────────────────
  { id: '69', categoryId: 'cold-drinks', name: 'סחוט טבעי',        price: 20, img: '/menu/jucie orange.webp' },
  { id: '70', categoryId: 'cold-drinks', name: 'קפה קר קרמל',      price: 13, img: '/menu/iced caramel.png',    sizes: [{ label: 'קטן', price: 13 }, { label: 'גדול', price: 18 }] },
  { id: '71', categoryId: 'cold-drinks', name: 'קפה קר וניל',      price: 13, img: '/menu/iced vanilla.png',    sizes: [{ label: 'קטן', price: 13 }, { label: 'גדול', price: 18 }] },
  { id: '72', categoryId: 'cold-drinks', name: 'קפה קר שוקולד',    price: 13, img: '/menu/iced chocolate.png',  sizes: [{ label: 'קטן', price: 13 }, { label: 'גדול', price: 18 }] },
  { id: '73', categoryId: 'cold-drinks', name: 'קפה קר',           price: 10, img: '/menu/cold coffee.webp',    sizes: [{ label: 'קטן', price: 10 }, { label: 'גדול', price: 15 }], extras: [{ label: 'קצפת', price: 3 }] },
  { id: '74', categoryId: 'cold-drinks', name: 'שוקו קר',          price: 10, img: '/menu/shokochocolate.webp', sizes: [{ label: 'קטן', price: 10 }, { label: 'גדול', price: 15 }], extras: [{ label: 'קצפת', price: 3 }] },
  { id: '76', categoryId: 'cold-drinks', name: 'מילקשייק תות',     price: 25, img: '/menu/tott.webp' },
  { id: '77', categoryId: 'cold-drinks', name: 'מילקשייק שוקולד',  price: 25, img: '/menu/shokomilk.webp' },
  { id: '78', categoryId: 'cold-drinks', name: 'שייקפה שוקולד',    price: 25, img: '/menu/shokomilk.webp',     desc: 'מילקשייק שוקולד ואספרסו' },
];
